"""Edited to imports

Revision ID: 216e3d6b4d28
Revises: bd9e86a47db2
Create Date: 2022-01-04 10:40:59.760596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216e3d6b4d28'
down_revision = 'bd9e86a47db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
