"""Added Document table

Revision ID: 6e21b37a6eec
Revises: 08f9723fa527
Create Date: 2022-01-02 15:20:08.983795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e21b37a6eec'
down_revision = '08f9723fa527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
