"""First migration

Revision ID: 85a274dbb8da
Revises: 6e21b37a6eec
Create Date: 2022-01-02 15:22:25.087354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a274dbb8da'
down_revision = '6e21b37a6eec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
