"""Adding foreign key for 1 to many relationship

Revision ID: bd9e86a47db2
Revises: f6f23a4783cd
Create Date: 2022-01-04 10:12:58.270018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd9e86a47db2'
down_revision = 'f6f23a4783cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
