"""Test

Revision ID: e180bb6d927b
Revises: 216e3d6b4d28
Create Date: 2022-01-04 11:08:55.841172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e180bb6d927b'
down_revision = '216e3d6b4d28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
