"""Test2

Revision ID: e4c2b3bafa63
Revises: e180bb6d927b
Create Date: 2022-01-04 11:15:04.767754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c2b3bafa63'
down_revision = 'e180bb6d927b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
