"""updatig tables

Revision ID: f6f23a4783cd
Revises: 8c26ec74f807
Create Date: 2022-01-03 11:58:30.221998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f23a4783cd'
down_revision = '8c26ec74f807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
